{
 "title": "Tessellation",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(process_uptime_seconds{application=~\"$application\"}, ip)"
    }
   },
   {
    "name": "peer_id",
    "label": "PeerId",
    "query": {
     "query": "label_values(process_uptime_seconds{application=~\"$application\", ip=~\"$ip\"}, peer_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L0 cluster size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(process_uptime_seconds{application=\"dag-l0\"})"
    }
   ]
  },
  {
   "title": "L1 cluster size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(process_uptime_seconds{application=\"dag-l1\"})"
    }
   ]
  },
  { "title": "Global Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Ordinal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "dag_global_snapshot_ordinal{ip=~\"$ip\", peer_id=~\"$peer_id\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Active tips",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max(dag_global_snapshot_tips_count{ip=~\"$ip\", peer_id=~\"$peer_id\", tip_type=\"active\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(dag_global_snapshot_tips_count{ip=~\"$ip\", peer_id=~\"$peer_id\", tip_type=\"active\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max(dag_global_snapshot_blocks_total{ip=~\"$ip\", peer_id=~\"$peer_id\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(dag_global_snapshot_blocks_total{ip=~\"$ip\", peer_id=~\"$peer_id\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "max(dag_global_snapshot_transactions_total{ip=~\"$ip\", peer_id=~\"$peer_id\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(dag_global_snapshot_transactions_total{ip=~\"$ip\", peer_id=~\"$peer_id\"})",
     "legendFormat": "Min"
    }
   ]
  },
  { "title": "Gossip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Rumor spreads by content type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (content_type_short) (increase(dag_rumors_spread_total{application=~\"$application\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rumor spreads by rumor type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rumor_type) (increase(dag_rumors_spread_total{application=~\"$application\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rumors spreaded/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ip) (increase(dag_rumors_spread_total{application=~\"$application\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]))",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Rumors exchanged/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (content_type_short) (increase(dag_rumors_sent_total{application=~\"$application\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]) + increase(dag_rumors_received_total{application=~\"$application\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes exchanged",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (content_type_short) (increase(dag_rumors_sent_bytes_total{application=~\"$application\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]) + increase(dag_rumors_received_bytes_total{application=~\"$application\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}