apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.7.4
          args: [ "-config.file=/etc/loki/config.yaml" ]
          ports:
            - containerPort: 3100
              name: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
              readOnly: false
            - name: loki-chunks-storage
              mountPath: /loki/chunks
              readOnly: false
            - name: loki-rules-storage
              mountPath: /loki/rules
              readOnly: false
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-chunks-storage
          emptyDir: { }
        - name: loki-rules-storage
          emptyDir: { }
