name: Metagraph L0 Validator

inputs:
  METAGRAPH_ID:
    required: true
  CL_PUBLIC_HTTP_PORT:
    required: true
  CL_P2P_HTTP_PORT:
    required: true
  CL_CLI_HTTP_PORT:
    required: true
  NODE_NUMBER:
    required: true

runs:
  using: "composite"
  steps:
    - name: Running Metagraph L0 validator - ${{ inputs.NODE_NUMBER }}
      env:
        CL_KEYSTORE: token-key.p12
        CL_KEYALIAS: token-key
        CL_PASSWORD: ${{ secrets.P12_GENESIS_FILE_PASSWORD }}
      run: |
        cd .github/config/containers/global-l0
        export GLOBAL_L0_NODE_ID=$(java -jar ../jars/cl-wallet.jar show-id)
        
        cd ../metagraph-l0/genesis
        export CURRENCY_L0_GENESIS_NODE_ID=$(java -jar ../../jars/cl-wallet.jar show-id)
        
        cd ../
        mkdir validator-1
        cd validator-1
        
        java -jar ../../jars/cl-keytool.jar generate
        
        export CL_PUBLIC_HTTP_PORT=${{ inputs.CL_PUBLIC_HTTP_PORT }}
        export CL_P2P_HTTP_PORT=${{ inputs.CL_P2P_HTTP_PORT }}
        export CL_CLI_HTTP_PORT=${{ inputs.CL_CLI_HTTP_PORT }}
        export CL_APP_ENV=dev
        export CL_ENV=dev
        export CL_COLLATERAL=0
        export CL_GLOBAL_L0_PEER_HTTP_HOST=127.0.0.1
        export CL_GLOBAL_L0_PEER_HTTP_PORT=9000
        export CL_GLOBAL_L0_PEER_ID=$GLOBAL_L0_NODE_ID
        export CL_L0_TOKEN_IDENTIFIER=${{ inputs.METAGRAPH_ID }}
        
        echo "GLOBAL_L0_NODE_ID=$GLOBAL_L0_NODE_ID"
        echo "CURRENCY_L0_GENESIS_NODE_ID=$CURRENCY_L0_GENESIS_NODE_ID"
        echo "CURRENCY_L0_VALIDATOR_1_NODE_ID=$(java -jar ../../jars/cl-wallet.jar show-id)"
        echo "METAGRAPH_IDENTIFIER=${{ inputs.METAGRAPH_ID }}"
        
        nohup java -jar ../../jars/metagraph-l0.jar run-validator --ip 127.0.0.1 > metagraph-l0-2.log 2>&1 &
        
        if node ../../../../action_scripts/check_if_node_started.js -url=http://127.0.0.1:9500/node/info -cluster_name=Metagraph-L0-${{ inputs.NODE_NUMBER }}; then
            sleep 5
            echo "Joining Metagraph l0 validator node ${{ inputs.NODE_NUMBER }} ..."
            curl -X POST http://127.0.0.1:9502/cluster/join -H "Content-type: application/json" -d "{ \"id\":\"$CURRENCY_L0_GENESIS_NODE_ID\", \"ip\": \"127.0.0.1\", \"p2pPort\": 9401 }"
            echo "Joined"
            exit 0
        fi