name: Metagraph L0 Genesis

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Create directories
      run: |
        cd .github/config
        mkdir -p containers/
        cd containers
        mkdir metagraph-l0
        mkdir -p jars

    - name: Copy genesis to Metagraph L0
      run: |
        cd .github/config
        cp genesis.csv containers/metagraph-l0

    - name: Generate Metagraph L0 JAR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sbt currencyL0/assembly keytool/assembly wallet/assembly
        
        mv modules/currency-l0/target/scala-2.13/tessellation-currency-l0-assembly-* .github/config/containers/jars/metagraph-l0.jar
        mv modules/keytool/target/scala-2.13/tessellation-keytool-assembly-* .github/config/containers/jars/cl-keytool.jar
        mv modules/wallet/target/scala-2.13/tessellation-wallet-assembly-* .github/config/containers/jars/cl-wallet.jar

    - name: Running Metagraph L0 genesis
      env:
        CL_KEYSTORE: token-key.p12
        CL_KEYALIAS: token-key
        CL_PASSWORD: ${{ secrets.P12_GENESIS_FILE_PASSWORD }}
      run: |
        cd .github/config/containers/global-l0
        export GLOBAL_L0_NODE_ID=$(java -jar ../jars/cl-wallet.jar show-id)
        
        cd ../metagraph-l0
        mkdir genesis
        cd genesis
        
        java -jar ../../jars/cl-keytool.jar generate
        export CURRENCY_L0_GENESIS_NODE_ID=$(java -jar ../../jars/cl-wallet.jar show-id)
        
        export CL_PUBLIC_HTTP_PORT=9400
        export CL_P2P_HTTP_PORT=9401
        export CL_CLI_HTTP_PORT=9402
        export CL_APP_ENV=dev
        export CL_ENV=dev
        export CL_COLLATERAL=0
        export CL_GLOBAL_L0_PEER_HTTP_HOST=127.0.0.1
        export CL_GLOBAL_L0_PEER_HTTP_PORT=9000
        export CL_GLOBAL_L0_PEER_ID=$GLOBAL_L0_NODE_ID
        
        echo "GLOBAL_L0_NODE_ID=$GLOBAL_L0_NODE_ID"
        echo "CURRENCY_L0_GENESIS_NODE_ID=$CURRENCY_L0_GENESIS_NODE_ID"
        
        nohup java -jar ../../jars/metagraph-l0.jar run-genesis ../genesis.csv --ip 127.0.0.1 > metagraph-l0-1.log 2>&1 &
        
        node ../../../../action_scripts/check_if_node_started.js -url=http://127.0.0.1:9400/node/info -cluster_name=Metagraph-L0-1