name: Metagraph L0 Genesis

inputs:
  CL_PUBLIC_HTTP_PORT:
    required: true
  CL_P2P_HTTP_PORT:
    required: true
  CL_CLI_HTTP_PORT:
    required: true
  IMPLEMENT_REWARDS:
    required: false

runs:
  using: "composite"
  steps:
    - name: Create directories
      shell: bash
      run: |
        cd .github/config
        mkdir -p containers/
        cd containers
        mkdir metagraph-l0
        mkdir -p jars

    - name: Copy genesis balances to Metagraph L0
      shell: bash
      run: |
        cd .github/config
        cp genesis.csv containers/metagraph-l0

    - name: Generate Metagraph L0 JAR
      shell: bash
      run: |
        cd .github/templates/project_template/

        if [[ "${{inputs.IMPLEMENT_REWARDS}}" != "" ]]; then
          echo "Adding basic rewards logic"
          cp ../../assets/basic_rewards_implementation.txt  modules/l0/src/main/scala/com/my/project_template/l0/Main.scala
        fi
        
        sbt currencyL0/assembly

    - name: Move Metagraph L0 JAR
      shell: bash
      run: |
        mv .github/templates/project_template/modules/l0/target/scala-2.13/project_template-currency-l0-assembly-* .github/config/containers/jars/metagraph-l0.jar

    - name: Running Metagraph L0 genesis
      shell: bash
      run: |
        export CL_KEYSTORE=token-key.p12
        export CL_KEYALIAS=token-key
        export CL_PASSWORD=password
        
        cd .github/config/containers/global-l0/genesis
        export GLOBAL_L0_NODE_ID=$(java -jar ../../jars/cl-wallet.jar show-id)
        
        cd ../../metagraph-l0
        mkdir genesis
        cd genesis
        
        java -jar ../../jars/cl-keytool.jar generate
        
        export CURRENCY_L0_GENESIS_NODE_ID=$(java -jar ../../jars/cl-wallet.jar show-id)
        
        export CL_PUBLIC_HTTP_PORT=${{ inputs.CL_PUBLIC_HTTP_PORT }}
        export CL_P2P_HTTP_PORT=${{ inputs.CL_P2P_HTTP_PORT }}
        export CL_CLI_HTTP_PORT=${{ inputs.CL_CLI_HTTP_PORT }}
        export CL_APP_ENV=dev
        export CL_COLLATERAL=0
        export CL_GLOBAL_L0_PEER_HTTP_HOST=127.0.0.1
        export CL_GLOBAL_L0_PEER_HTTP_PORT=9000
        export CL_GLOBAL_L0_PEER_ID=$GLOBAL_L0_NODE_ID
        
        echo "GLOBAL_L0_NODE_ID=$GLOBAL_L0_NODE_ID"
        echo "CURRENCY_L0_GENESIS_NODE_ID=$CURRENCY_L0_GENESIS_NODE_ID"
        
        nohup java -jar ../../jars/metagraph-l0.jar create-genesis ../genesis.csv --ip 127.0.0.1 > metagraph-l0-create-genesis.log 2>&1 &&
        
        nohup java -jar ../../jars/metagraph-l0.jar run-genesis ../genesis.snapshot --ip 127.0.0.1 > metagraph-l0-genesis.log 2>&1 &
        
        node ../../../../action_scripts/check_if_node_started/index.js -url=http://127.0.0.1:${{ inputs.CL_PUBLIC_HTTP_PORT }}/node/info -cluster_name=Metagraph-L0-Genesis
