apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: l0-validator
      custom:
        buildCommand: |
          sbt core/assembly keytool/assembly && \
            docker build $BUILD_CONTEXT --file kubernetes/l0.Dockerfile --tag $IMAGE --build-arg BUILD_VERSION=$(cut -d \" -f 2 version.sbt) --platform linux/amd64 && \
              [[ "$PUSH_IMAGE" == "true" ]] && docker push $IMAGE || echo "Skip pushing image"
        dependencies:
          paths:
            - modules/**/src/main/**/*.scala
            - "*.sbt"
            - project/*.scala
            - project/**.sbt
            - project/build.properties
    - image: l1-validator
      custom:
        buildCommand: |
          sbt dagL1/assembly keytool/assembly && \
            docker build $BUILD_CONTEXT --file kubernetes/l1.Dockerfile --tag $IMAGE --build-arg BUILD_VERSION=$(cut -d \" -f 2 version.sbt) --platform linux/amd64 && \
              [[ "$PUSH_IMAGE" == "true" ]] && docker push $IMAGE || echo "Skip pushing image"
        dependencies:
          paths:
            - modules/**/src/main/**/*.scala
            - "*.sbt"
            - project/*.scala
            - project/**.sbt
            - project/build.properties

deploy:
  kustomize:
    paths:
      - kubernetes/l0-cluster
      - kubernetes/l1-cluster
      - kubernetes/grafana
      - kubernetes/prometheus
  logs:
    prefix: podAndContainer

portForward:
  - resourceType: service
    resourceName: l0-initial-validator
    port: 9000
    localPort: 9000
  - resourceType: service
    resourceName: l1-initial-validator
    port: 9000
    localPort: 9100
  - resourceType: service
    resourceName: grafana
    port: 8000
    localPort: 8000

profiles:
  - name: logPods
    deploy:
      logs:
        prefix: podAndContainer
  - name: onlyL0
    patches:
      - op: remove
        path: /build/artifacts/1
      - op: remove
        path: /deploy/kustomize/paths/1
      - op: remove
        path: /portForward/1
