apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-deployment.yaml
  - prometheus-service.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yaml
