services:
  node-exporter:
    image: prom/node-exporter:latest
    user: root
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "${NODE_EXPORTER_BIND_INTERFACE:-127.0.0.1}:9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
