name: DAG L1 Validator

inputs:
  CL_PUBLIC_HTTP_PORT:
    required: true
  CL_P2P_HTTP_PORT:
    required: true
  CL_CLI_HTTP_PORT:
    required: true
  CL_GLOBAL_L0_PEER_HTTP_PORT:
    required: true
  CL_L1_INITIAL_VALIDATOR_P2P_PORT:
    required: true
  NODE_NUMBER:
    required: true

runs:
  using: "composite"
  steps:
    - name: Running DAG L1 validator - ${{ inputs.NODE_NUMBER }}
      shell: bash
      run: |
        export CL_KEYSTORE=token-key.p12
        export CL_KEYALIAS=token-key
        export CL_PASSWORD=password
        
        cd .github/config/containers/global-l0/genesis
        export GLOBAL_L0_NODE_ID=$(java -jar ../../jars/cl-wallet.jar show-id)

        cd ../../dag-l1/initial-validator
        export DAG_L1_INITIAL_VALIDATOR_NODE_ID=$(java -jar ../../jars/cl-wallet.jar show-id)

        cd ../
        mkdir validator-${{ inputs.NODE_NUMBER }}
        cd validator-${{ inputs.NODE_NUMBER }}

        java -jar ../../jars/cl-keytool.jar generate

        export CL_PUBLIC_HTTP_PORT=${{ inputs.CL_PUBLIC_HTTP_PORT }}
        export CL_P2P_HTTP_PORT=${{ inputs.CL_P2P_HTTP_PORT }}
        export CL_CLI_HTTP_PORT=${{ inputs.CL_CLI_HTTP_PORT }}
        export CL_APP_ENV=dev
        export CL_COLLATERAL=0
        export CL_L0_PEER_HTTP_HOST=127.0.0.1
        export CL_L0_PEER_HTTP_PORT=${{ inputs.CL_GLOBAL_L0_PEER_HTTP_PORT }}
        export CL_L0_PEER_ID=$GLOBAL_L0_NODE_ID

        echo "GLOBAL_L0_NODE_ID= $GLOBAL_L0_NODE_ID"
        echo "DAG_L1_INITIAL_VALIDATOR_NODE_ID= $DAG_L1_INITIAL_VALIDATOR_NODE_ID"
        echo "DAG_L1_VALIDATOR_1_NODE_ID= $(java -jar ../../jars/cl-wallet.jar show-id)"

        nohup java -jar ../../jars/dag-l1.jar run-validator --ip 127.0.0.1 > dag-l1-validator-${{ inputs.NODE_NUMBER }}.log 2>&1 &

        if node ../../../../action_scripts/check_if_node_started/index.js -url=http://127.0.0.1:${{ inputs.CL_PUBLIC_HTTP_PORT }}/node/info -cluster_name=DAG-L1-Validator-${{ inputs.NODE_NUMBER }}; then
          sleep 5
          echo "Joining dag-l1 validator node ${{ inputs.NODE_NUMBER }} ..."
          curl -X POST http://127.0.0.1:${{ inputs.CL_CLI_HTTP_PORT }}/cluster/join -H "Content-type: application/json" -d "{ \"id\":\"$DAG_L1_INITIAL_VALIDATOR_NODE_ID\", \"ip\": \"127.0.0.1\", \"p2pPort\": ${{ inputs.CL_L1_INITIAL_VALIDATOR_P2P_PORT }} }"
          echo "Joined"
          exit 0
        fi