name: Metagraph L1 - Data Initial Validator

inputs:
  METAGRAPH_ID:
    required: true
  METAGRAPH_NAME:
    required: true
  CL_PUBLIC_HTTP_PORT:
    required: true
  CL_P2P_HTTP_PORT:
    required: true
  CL_CLI_HTTP_PORT:
    required: true
  CL_GLOBAL_L0_PEER_HTTP_PORT:
    required: true
  CL_L0_PEER_HTTP_PORT:
    required: true

runs:
  using: "composite"
  steps:
    - name: Running Metagraph L1 - Data Initial Validator
      shell: bash
      env:
        CL_KEYSTORE: token-key.p12
        CL_KEYALIAS: token-key
        CL_PASSWORD: password
        CL_PUBLIC_HTTP_PORT: ${{ inputs.CL_PUBLIC_HTTP_PORT }}
        CL_P2P_HTTP_PORT: ${{ inputs.CL_P2P_HTTP_PORT }}
        CL_CLI_HTTP_PORT: ${{ inputs.CL_CLI_HTTP_PORT }}
        CL_APP_ENV: dev
        CL_COLLATERAL: 0
        CL_GLOBAL_L0_PEER_HTTP_HOST: 127.0.0.1
        CL_GLOBAL_L0_PEER_HTTP_PORT: ${{ inputs.CL_GLOBAL_L0_PEER_HTTP_PORT }}
        CL_L0_PEER_HTTP_HOST: 127.0.0.1
        CL_L0_PEER_HTTP_PORT: ${{ inputs.CL_L0_PEER_HTTP_PORT }}
        CL_L0_TOKEN_IDENTIFIER: ${{ inputs.METAGRAPH_ID }}
      run: |
        ROOT_DIRECTORY=$(pwd)

        cd $ROOT_DIRECTORY/.github/code/hypergraph/dag-l0/genesis-node
        GLOBAL_L0_NODE_ID=$(java -jar $ROOT_DIRECTORY/.github/code/shared_jars/cl-wallet.jar show-id)

        cd $ROOT_DIRECTORY/.github/code/metagraphs/${{inputs.METAGRAPH_NAME}}/metagraph-l0/genesis-node
        CURRENCY_L0_GENESIS_NODE_ID=$(java -jar $ROOT_DIRECTORY/.github/code/shared_jars/cl-wallet.jar show-id)

        cd $ROOT_DIRECTORY/.github/code/metagraphs/${{inputs.METAGRAPH_NAME}}/data-l1/initial-validator
        java -jar $ROOT_DIRECTORY/.github/code/shared_jars/cl-keytool.jar generate

        export CL_GLOBAL_L0_PEER_ID=$GLOBAL_L0_NODE_ID
        export CL_L0_PEER_ID=$CURRENCY_L0_GENESIS_NODE_ID
        touch data-l1-initial-validator.log
        nohup stdbuf -o0 -e0 java -Denvironment=dev -jar $ROOT_DIRECTORY/.github/code/metagraphs/${{inputs.METAGRAPH_NAME}}/data-l1/data-l1.jar run-initial-validator --ip 127.0.0.1 > data-l1-initial-validator.log 2>&1 &
        sleep 5

    - name: Check if node started
      shell: bash
      env:
        CL_PUBLIC_HTTP_PORT: ${{ inputs.CL_PUBLIC_HTTP_PORT }}
      run: |
        node .github/action_scripts/check_if_node_started.js -url=http://127.0.0.1:${CL_PUBLIC_HTTP_PORT}/node/info -cluster_name=Data-L1-Initial-Validator