apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-deployment.yaml
  - http-proxy-service.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
