name: Global L0 Genesis

runs:
  using: "composite"
  steps:
    - name: Create directories
      run: |
        cd .github/config
        mkdir -p containers/
        cd containers
        mkdir global-l0
        mkdir -p jars

    - name: Copy genesis to Global L0
      run: |
        cd .github/config
        cp genesis.csv containers/global-l0

    - name: Generate Global L0 JAR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sbt core/assembly keytool/assembly wallet/assembly
        
        mv modules/core/target/scala-2.13/tessellation-core-assembly-* .github/config/containers/jars/global-l0.jar
        mv modules/keytool/target/scala-2.13/tessellation-keytool-assembly-* .github/config/containers/jars/cl-keytool.jar
        mv modules/wallet/target/scala-2.13/tessellation-wallet-assembly-* .github/config/containers/jars/cl-wallet.jar

    - name: Running global-l0
      env:
        CL_KEYSTORE: token-key.p12
        CL_KEYALIAS: token-key
        CL_PASSWORD: ${{ secrets.P12_GENESIS_FILE_PASSWORD }}
      run: |
        cd .github/config/containers/global-l0
        java -jar ../jars/cl-keytool.jar generate
        
        export CL_PUBLIC_HTTP_PORT=9000
        export CL_P2P_HTTP_PORT=9001
        export CL_CLI_HTTP_PORT=9002
        export CL_APP_ENV=dev
        export CL_ENV=dev
        export CL_COLLATERAL=0
        
        nohup java -jar ../jars/global-l0.jar run-genesis genesis.csv --ip 127.0.0.1 > global-l0.log 2>&1 &
        
        node ../../../action_scripts/check_if_node_started.js -url=http://127.0.0.1:9000/node/info -cluster_name=Global-L0