/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.rosetta.server.model
import org.tessellation.rosetta.server.model.dag.schema.AccountBalanceResponseMetadata

case class AccountBalanceResponse(
  blockIdentifier: BlockIdentifier,
  /* A single account may have a balance in multiple currencies. */
  balances: List[Amount],
  /* Account-based blockchains that utilize a nonce or sequence number should include that number in the metadata. This number could be unique to the identifier or global across the account address. */
  metadata: Option[AccountBalanceResponseMetadata]
)
