/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.rosetta.server.model
import org.tessellation.rosetta.server.model.dag.schema.AccountIdentifierMetadata

case class AccountIdentifier(
  /* The address may be a cryptographic public key (or some encoding of it) or a provided username. */
  address: String,
  subAccount: Option[SubAccountIdentifier],
  /* Blockchains that utilize a username model (where the address is not a derivative of a cryptographic public key) should specify the public key(s) owned by the address in metadata. */
  metadata: Option[AccountIdentifierMetadata]
)
