/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.rosetta.server.model

case class BlockIdentifier(
  /* This is also known as the block height. */
  index: Long,
  /* This should be normalized according to the case specified in the block_hash_case network options. */
  hash: String
)
