/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.rosetta.server.model

case class EventsBlocksRequest(
  networkIdentifier: NetworkIdentifier,
  /* offset is the offset into the event stream to sync events from. If this field is not populated, we return the limit events backwards from tip. If this is set to 0, we start from the beginning. */
  offset: Option[Long],
  /* limit is the maximum number of events to fetch in one call. The implementation may return <= limit events. */
  limit: Option[Long]
)
