/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.rosetta.server.model
//import derevo.cats.show
//import derevo.circe.magnolia.{decoder, encoder}
//import derevo.derive
import org.tessellation.rosetta.server.model.dag.schema.GenericMetadata

//
case class NetworkRequest(
  networkIdentifier: NetworkIdentifier,
  metadata: Option[GenericMetadata]
)
