/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.rosetta.server.model

case class NetworkStatusResponse(
  currentBlockIdentifier: BlockIdentifier,
  currentBlockTimestamp: Long,
  genesisBlockIdentifier: BlockIdentifier,
  oldestBlockIdentifier: Option[BlockIdentifier],
  syncStatus: Option[SyncStatus],
  peers: List[Peer]
)
