/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.rosetta.server.model

case class SearchTransactionsRequest(
  networkIdentifier: NetworkIdentifier,
  operator: Option[Operator],
  /* max_block is the largest block index to consider when searching for transactions. If this field is not populated, the current block is considered the max_block. If you do not specify a max_block, it is possible a newly synced block will interfere with paginated transaction queries (as the offset could become invalid with newly added rows). */
  maxBlock: Option[Long],
  /* offset is the offset into the query result to start returning transactions. If any search conditions are changed, the query offset will change and you must restart your search iteration. */
  offset: Option[Long],
  /* limit is the maximum number of transactions to return in one call. The implementation may return <= limit transactions. */
  limit: Option[Long],
  transactionIdentifier: Option[TransactionIdentifier],
  accountIdentifier: Option[AccountIdentifier],
  coinIdentifier: Option[CoinIdentifier],
  currency: Option[Currency],
  /* status is the network-specific operation type. */
  status: Option[String],
  /* type is the network-specific operation type. */
  `type`: Option[String],
  /* address is AccountIdentifier.Address. This is used to get all transactions related to an AccountIdentifier.Address, regardless of SubAccountIdentifier. */
  address: Option[String],
  /* success is a synthetic condition populated by parsing network-specific operation statuses (using the mapping provided in `/network/options`). */
  success: Option[Boolean]
)
