/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.rosetta.server.model

case class SigningPayload(
  /* [DEPRECATED by `account_identifier` in `v1.4.4`] The network-specific address of the account that should sign the payload. */
  address: Option[String],
  accountIdentifier: Option[AccountIdentifier],
  /* Hex-encoded string of the payload bytes. */
  hexBytes: String,
  signatureType: Option[String]
)
