state-after-joining = WaitingForDownload

peer-discovery {
  delay {
    check-peers-attempt-delay = 1 minute
    check-peers-max-delay = 10 minutes
    additional-discovery-delay = 0 minutes
    min-peers = 1
  }
}

health-check {
  remove-unresponsive-parallel-peers-after = 10 seconds
  request-proposals-after = 8 seconds
}

snapshot {
  consensus {
    time-trigger-interval = 43 seconds
    declaration-timeout = 15 seconds
    declaration-range-limit = 3
    lock-duration = 5 seconds
    peers-declaration-timeout = 10 seconds
    active-phase-retry-interval = 1 second
    round-completion-delay = 1 second

    event-cutter {
      max-binary-size-bytes = 20971520
      max-update-node-parameters-size = 100
    }
  }

  in-memory-capacity = 10

  snapshot-path = "data/snapshot"
  snapshot-path = ${?CL_SNAPSHOT_STORED_PATH}

  incremental-tmp-snapshot-path = "data/incremental_snapshot_tmp"
  incremental-tmp-snapshot-path = ${?CL_INCREMENTAL_SNAPSHOT_TMP_STORED_PATH}

  incremental-persisted-snapshot-path = "data/incremental_snapshot"
  incremental-persisted-snapshot-path = ${?CL_INCREMENTAL_SNAPSHOT_STORED_PATH}

  snapshot-info-path = "data/snapshot_info"
  snapshot-info-path = ${?CL_SNAPSHOT_INFO_PATH}

  calculated-state-path = "data/calculated_state"
  calculated-state-path = ${?CL_CALCULATED_STATE_PATH}

  global-snapshots-with-state-path= "data/global_snapshots/snapshots_with_state"
  global-snapshots-with-state-path = ${?CL_GLOBAL_SNAPSHOTS_WITH_STATE_PATH}

  global-snapshots-with-state-deltas-path= "data/global_snapshots/snapshots_with_state_deltas"
  global-snapshots-with-state-deltas-path = ${?CL_GLOBAL_SNAPSHOTS_WITH_STATE_DELTAS_PATH}

  max-global-snapshots-with-state-stored = 2
  max-global-snapshots-with-state-deltas-stored = 100

  combined-snapshot-checkpoint-path = "data/combined_snapshot_checkpoint"
  combined-snapshot-checkpoint-path = ${?CL_COMBINED_SNAPSHOT_CHECKPOINT_PATH}
}

