name: DAG L0 Cluster

inputs:
  PORT_PREFIX:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Global L0 Genesis
      uses: "./.github/templates/actions/hypergraph/dag_l0/genesis"
      with:
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}00
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}01
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}02

    - name: Run Global L0 Validator - 1
      uses: "./.github/templates/actions/hypergraph/dag_l0/validator"
      with:
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}10
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}11
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}12
        CL_L0_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}01
        NODE_NUMBER: 1

    - name: Run Global L0 Validator - 2
      uses: "./.github/templates/actions/hypergraph/dag_l0/validator"
      with:
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}20
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}21
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}22
        CL_L0_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}01
        NODE_NUMBER: 2