name: Global L0 Cluster

runs:
  using: "composite"
  steps:
    - name: Run Global L0 Genesis
      with:
        CL_PUBLIC_HTTP_PORT: 9000
        CL_P2P_HTTP_PORT: 9001
        CL_CLI_HTTP_PORT: 9002
      uses: "./.github/templates/global_l0/genesis"