name: Metagraph L1 - Data Cluster

inputs:
  METAGRAPH_NAME:
    required: true
  PORT_PREFIX:
    required: true
  METAGRAPH_L0_PEER_HTTP_PORT:
    required: true
  GLOBAL_L0_PEER_HTTP_PORT:
    required: true
  EXTENDED_L1:
    required: false

runs:
  using: "composite"
  steps:
    - name: Get the Metagraph ID
      shell: bash
      run: |
        cd .github/code/metagraphs/${{inputs.METAGRAPH_NAME}}/metagraph-l0/genesis-node
        export METAGRAPH_ID=$(head -n 1 genesis.address)
        echo "METAGRAPH_ID=$METAGRAPH_ID" >> $GITHUB_ENV

    - name: Run Metagraph L1 - Data Initial Validator
      uses: "./.github/templates/actions/metagraph/data_l1/initial_validator"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        METAGRAPH_NAME: ${{ inputs.METAGRAPH_NAME }}
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}00
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}01
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}02
        CL_GLOBAL_L0_PEER_HTTP_PORT: ${{ inputs.GLOBAL_L0_PEER_HTTP_PORT }}
        CL_L0_PEER_HTTP_PORT: ${{ inputs.METAGRAPH_L0_PEER_HTTP_PORT }}

    - name: Run Metagraph L1 - Data Validator - 1
      uses: "./.github/templates/actions/metagraph/data_l1/validator"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        METAGRAPH_NAME: ${{ inputs.METAGRAPH_NAME }}
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}10
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}11
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}12
        CL_GLOBAL_L0_PEER_HTTP_PORT: ${{ inputs.GLOBAL_L0_PEER_HTTP_PORT }}
        CL_L0_PEER_HTTP_PORT: ${{ inputs.METAGRAPH_L0_PEER_HTTP_PORT }}
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: ${{ inputs.PORT_PREFIX }}01
        NODE_NUMBER: 1

    - name: Run Metagraph L1 - Data Validator - 2
      uses: "./.github/templates/actions/metagraph/data_l1/validator"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        METAGRAPH_NAME: ${{ inputs.METAGRAPH_NAME }}
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}20
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}21
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}22
        CL_GLOBAL_L0_PEER_HTTP_PORT: ${{ inputs.GLOBAL_L0_PEER_HTTP_PORT }}
        CL_L0_PEER_HTTP_PORT: ${{ inputs.METAGRAPH_L0_PEER_HTTP_PORT }}
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: ${{ inputs.PORT_PREFIX }}01
        NODE_NUMBER: 2

    - name: Run Metagraph L1 - Data Validator - 3
      uses: "./.github/templates/actions/metagraph/data_l1/validator"
      if: ${{ inputs.EXTENDED_L1 == 'true' }}
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        METAGRAPH_NAME: ${{ inputs.METAGRAPH_NAME }}
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}30
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}31
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}32
        CL_GLOBAL_L0_PEER_HTTP_PORT: ${{ inputs.GLOBAL_L0_PEER_HTTP_PORT }}
        CL_L0_PEER_HTTP_PORT: ${{ inputs.METAGRAPH_L0_PEER_HTTP_PORT }}
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: ${{ inputs.PORT_PREFIX }}01
        NODE_NUMBER: 3

    - name: Run Metagraph L1 - Data Validator - 4
      uses: "./.github/templates/actions/metagraph/data_l1/validator"
      if: ${{ inputs.EXTENDED_L1 == 'true' }}
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        METAGRAPH_NAME: ${{ inputs.METAGRAPH_NAME }}
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}40
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}41
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}42
        CL_GLOBAL_L0_PEER_HTTP_PORT: ${{ inputs.GLOBAL_L0_PEER_HTTP_PORT }}
        CL_L0_PEER_HTTP_PORT: ${{ inputs.METAGRAPH_L0_PEER_HTTP_PORT }}
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: ${{ inputs.PORT_PREFIX }}01
        NODE_NUMBER: 4

    - name: Run Metagraph L1 - Data Validator - 5
      uses: "./.github/templates/actions/metagraph/data_l1/validator"
      if: ${{ inputs.EXTENDED_L1 == 'true' }}
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        METAGRAPH_NAME: ${{ inputs.METAGRAPH_NAME }}
        CL_PUBLIC_HTTP_PORT: ${{ inputs.PORT_PREFIX }}50
        CL_P2P_HTTP_PORT: ${{ inputs.PORT_PREFIX }}51
        CL_CLI_HTTP_PORT: ${{ inputs.PORT_PREFIX }}52
        CL_GLOBAL_L0_PEER_HTTP_PORT: ${{ inputs.GLOBAL_L0_PEER_HTTP_PORT }}
        CL_L0_PEER_HTTP_PORT: ${{ inputs.METAGRAPH_L0_PEER_HTTP_PORT }}
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: ${{ inputs.PORT_PREFIX }}01
        NODE_NUMBER: 5