{
 "title": "Network Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Snapshot Rate (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gs_timing_monitor_ordinal_change_s{layer=\"gl0_mainnet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "epochProgress Rate (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gs_timing_monitor_epochProgress_change_s{layer=\"gl0_mainnet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gl0 State Size (MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gs_state_monitor_state_size{layer=\"gl0_mainnet\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Streaming Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gs_snapshot_streaming_ordinal_diff{layer=\"gl0_mainnet\"} > bool 20",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Uptime % 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time((gs_timing_monitor_ordinal_change_s{layer=\"gl0_mainnet\"} > bool 0)[24h:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GL0 Node States",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node_state) (gs_cluster_node_state{layer=\"gl0_mainnet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Global Network ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Global Snapshot Ordinal Seconds",
   "type": "timeseries",
   "description": "Average time of ordinal change over a rolling 5 min period. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "gs_timing_monitor_ordinal_change_s{layer=\"gl0_mainnet\"}",
     "legendFormat": "snapshotOrdinalS"
    }
   ]
  },
  {
   "title": "GL0 Node Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(node_state) (gs_cluster_node_state{layer=\"gl0_mainnet\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gs_cluster_node_state{layer=\"gl0_mainnet\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "EpochProgress Avg Seconds",
   "type": "timeseries",
   "description": "Average time of epochProgress change over rolling 5 min period. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "gs_timing_monitor_epochProgress_change_s{layer=\"gl0_mainnet\"}",
     "legendFormat": "epochProgressAvgS"
    }
   ]
  },
  {
   "title": "DAG L1 Node Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(node_state) (gs_cluster_node_state{layer=\"dagl1_mainnet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Snapshot Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Snapshot Streaming Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "gs_snapshot_streaming_be_ordinal{layer=\"gl0_mainnet\"}",
     "legendFormat": "Snapshot Streaming"
    },
    {
     "expr": "gs_snapshot_streaming_network_ordinal{layer=\"gl0_mainnet\"}",
     "legendFormat": "Network (Source Node)"
    }
   ]
  },
  {
   "title": "Snapshot Differential (Network vs streaming)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "gs_snapshot_streaming_ordinal_diff{layer=\"gl0_mainnet\"}",
     "legendFormat": "Diff"
    }
   ]
  },
  {
   "title": "Snapshot Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(gs_state_monitor_snapshot_size{layer=\"gl0_mainnet\"}) by (job)",
     "legendFormat": "Snapshot (on chain) MB"
    },
    {
     "expr": "sum(gs_state_monitor_state_size{layer=\"gl0_mainnet\"}) by (job)",
     "legendFormat": "Snapshot State MB"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_activeAllowSpends{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: activeAllowSpends"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_activeDelegatedStakes{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: activeDelegatedStakes"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_activeNodeCollaterals{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: activeNodeCollaterals"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_activeTokenLocks{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: activeTokenLocks"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_balances{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: balances"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_delegatedStakesWithdrawals{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: delegatedStakesWithdrawals"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_lastAllowSpendRefs{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: lastAllowSpendRefs"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_lastCurrencySnapshots{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: lastCurrencySnapshots"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_lastCurrencySnapshotsProofs{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: lastCurrencySnapshotProofs"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_lastStateChannelSnapshotHashes{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: lastStateChannelSnapshotHashes"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_lastTokenLockRefs{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: lastTokenLockRefs"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_lastTxRefs{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: lastTxRefs"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_nodeCollateralWithdrawals{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: nodeCollateralWithdrawals"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_tokenLockBalances{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: tokenLockBalances"
    },
    {
     "expr": "sum by(job) (gs_state_monitor_state_size_updateNodeParameters{layer=\"gl0_mainnet\"})",
     "legendFormat": "State size: updateNodeParameters"
    },
    {}
   ]
  },
  {
   "title": "Metagraph Snapshot Count",
   "type": "timeseries",
   "description": "Sampling of metagraph snapshots at 5 minute intervals",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(metagraphId) (avg_over_time(gs_state_monitor_metagraph_snapshot_count{layer=\"gl0_mainnet\"}[1h]))",
     "legendFormat": "{{metagraphId}}"
    }
   ]
  }
 ]
}