#!/bin/sh
#ulimit -c unlimited
#ulimit -n 60036
export CL_EXTERNAL_IP=$(cat external_host_ip) &&\
export CL_KEYSTORE=key.p12 && \
#export CL_STOREPASS=storepass && \
export CL_PASSWORD=storepass && \
#export CL_KEYPASS=keypass && \
export CL_KEYALIAS=alias && \
java "-Dcom.sun.management.jmxremote" \
"-Dcom.sun.management.jmxremote.port=9010" \
"-Dcom.sun.management.jmxremote.rmi.port=9011" \
"-Dcom.sun.management.jmxremote.local.only=false" \
"-Dcom.sun.management.jmxremote.authenticate=false" \
"-Dcom.sun.management.jmxremote.ssl=false" \
"-Dlogback.configurationFile=/home/admin/constellation/logback.xml" \
"-XX:+HeapDumpOnOutOfMemoryError" \
"-Xms1024M" \
"-Xmx8G" \
"-Xss256K" \
-Djava.rmi.server.hostname=$(cat external_host_ip) \
-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n \
-cp dag.jar org.tessellation.Main run-genesis data.csv --ip $CL_EXTERNAL_IP \
--public-port 9000 --p2p-port 9001 --cli-port 9003 -e testnet
