server:
  disable: true

client:
  url: "http://loki:3100/loki/api/v1/push"

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/app/json_logs/*.json.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: '"@timestamp"'
            message: message
            level: level
            logger_name: logger_name
            ip: ip
            application: application
            peer_id_short: peer_id_short
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: message
      - template:
          source: log_file
          template: '{{ base .filename | trimSuffix ".json.log" }}'
      - labels:
          level:
          ip:
          application:
          peer_id_short:
          log_file:
      - labeldrop: [ "filename" ]
