name: Metagraph L0 Cluster

inputs:
  IMPLEMENT_REWARDS:
    required: false

runs:
  using: "composite"
  steps:
    - name: Run Metagraph L0 Genesis
      with:
        CL_PUBLIC_HTTP_PORT: 9400
        CL_P2P_HTTP_PORT: 9401
        CL_CLI_HTTP_PORT: 9402
        IMPLEMENT_REWARDS: ${{ inputs.IMPLEMENT_REWARDS }}
      uses: "./.github/templates/metagraph_l0/genesis"

    - name: Get the Metagraph ID
      shell: bash
      run: |
        cd .github/config/containers/metagraph-l0/genesis
        export METAGRAPH_ID=$(tail metagraph-l0-genesis.log -n 1000 | grep -o "Address from genesis data is .*" | grep -o "DAG.*")
        echo "METAGRAPH_ID=$METAGRAPH_ID"
        echo "METAGRAPH_ID=$METAGRAPH_ID" >> $GITHUB_ENV

    - name: Run Metagraph L0 Validator - 1
      uses: "./.github/templates/metagraph_l0/validator"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        CL_PUBLIC_HTTP_PORT: 9500
        CL_P2P_HTTP_PORT: 9501
        CL_CLI_HTTP_PORT: 9502
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L0_P2P_HTTP_PORT: 9401
        NODE_NUMBER: 1

    - name: Run Metagraph L0 Validator - 2
      uses: "./.github/templates/metagraph_l0/validator"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        CL_PUBLIC_HTTP_PORT: 9600
        CL_P2P_HTTP_PORT: 9601
        CL_CLI_HTTP_PORT: 9602
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L0_P2P_HTTP_PORT: 9401
        NODE_NUMBER: 2