name: Metagraph L0 Cluster

runs:
  using: "composite"
  steps:
    - name: Run Metagraph L0 Genesis
      uses: "./.github/templates/metagraph_l0/genesis/action.yml"

    - name: Get the Metagraph ID
      run: |
        cd .github/config/containers/metagraph-l0/genesis
        export METAGRAPH_ID=$(tail currency-l0-1.log -n 1000 | grep -o "Address from genesis data is .*" | grep -o "DAG.*")
        echo "METAGRAPH_ID=$METAGRAPH_ID"
        echo "METAGRAPH_ID=$METAGRAPH_ID" >> $GITHUB_ENV

    - name: Run Metagraph L0 Validator - 1
      uses: "./.github/templates/metagraph_l0/validator/action.yml"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        CL_PUBLIC_HTTP_PORT: 9500
        CL_P2P_HTTP_PORT: 9501
        CL_CLI_HTTP_PORT: 9502
        NODE_NUMBER: 1

    - name: Run Metagraph L0 Validator - 2
      uses: "./.github/templates/metagraph_l0/validator/action.yml"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        CL_PUBLIC_HTTP_PORT: 9600
        CL_P2P_HTTP_PORT: 9601
        CL_CLI_HTTP_PORT: 9602
        NODE_NUMBER: 2