name: DAG L1 Cluster

runs:
  using: "composite"
  steps:
    - name: Run DAG L1 Initial Validator
      uses: "./.github/templates/dag_l1/initial_validator"
      with:
        CL_PUBLIC_HTTP_PORT: 9100
        CL_P2P_HTTP_PORT: 9101
        CL_CLI_HTTP_PORT: 9102
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000

    - name: Run DAG L1 Validator - 1
      uses: "./.github/templates/dag_l1/validator"
      with:
        CL_PUBLIC_HTTP_PORT: 9200
        CL_P2P_HTTP_PORT: 9201
        CL_CLI_HTTP_PORT: 9202
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: 9101
        NODE_NUMBER: 1

    - name: Run DAG L1 Validator - 2
      uses: "./.github/templates/dag_l1/validator"
      with:
        CL_PUBLIC_HTTP_PORT: 9300
        CL_P2P_HTTP_PORT: 9301
        CL_CLI_HTTP_PORT: 9302
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: 9101
        NODE_NUMBER: 2