/**
  * Rosetta
  * Build Once. Integrate Your Blockchain Everywhere.
  *
  * The version of the OpenAPI document: 1.4.12
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  */

package org.tessellation.dag.l1.rosetta.model

import org.tessellation.dag.l1.rosetta.model.dag.schema._

case class Transaction(
  transactionIdentifier: TransactionIdentifier,
  operations: List[Operation],
  relatedTransactions: Option[List[RelatedTransaction]],
  /* Transactions that are related to other transactions (like a cross-shard transaction) should include the tranaction_identifier of these transactions in the metadata. */
  metadata: Option[GenericMetadata]
)
