name: Check scala code

on:
  pull_request: {}
  push:
    branches:
      - develop
      - hotfix/*
      - release/*
jobs:
  build:
    name: Check scala code
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java and scala
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          JAVA_VERSION: 11
        uses: "./.github/templates/actions/setup_java_and_scala"

      - name: Run with 11 🚀
        run: sbt --error 'scalafixAll --check --rules OrganizeImports;scalafmtCheckAll;test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}