name: Check scala code

on:
  pull_request: {}
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        scala: [ 2.12.10 ]
        java: [ adopt@1.8 ]
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Run with ${{ matrix.java }} 🚀"
        run: sbt 'scalafixAll --check --rules OrganizeImports;scalafmtCheckAll;test;it:test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
