name: Check scala code

on:
  pull_request: {}
  push:
    branches:
      - develop
      - hotfix/*
      - release/*

jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java:
          - zulu@1.8.282
          - openjdk@1.11.0
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java and scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}

      - name: Cache for sbt & coursier ♨️
        uses: coursier/cache-action@v6
        id: coursier-cache

      - name: Fetch Dependencies
        if: steps.coursier-cache.outputs.cache-hit-coursier != 'true'
        run: sbt +update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run with ${{ matrix.java }} 🚀
        run: sbt 'scalafixAll --check --rules OrganizeImports;scalafmtCheckAll;test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
