name: Check scala code

on:
  pull_request: {}
  push:
    branches:
      - feature/node2.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - graalvm8-ce
          - graalvm11-ce
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v13

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: tesselation
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Run with ${{ matrix.java }} 🚀"
        run: nix-shell --argstr jdk "${{ matrix.java }}" --run "sbt 'scalafixAll --rules OrganizeImports --check;scalafmtCheckAll;test;it:test'"
