name: Check scala code

on:
  pull_request: {}
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - jdk8
          - jdk11
    steps:
      - uses: actions/checkout@v2.4.0

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: tessellation
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Run with ${{ matrix.java }} 🚀"
        run: nix-shell --argstr jdk "${{ matrix.java }}" --run "sbt 'scalafixAll --check --rules OrganizeImports;scalafmtCheckAll;test'" nix/ci.nix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
