name: Setup environment

on:
  workflow_call:

jobs:
  setup-hypergraph:
    name: Setup Hypergraph
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java and scala
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          JAVA_VERSION: 11
        uses: "./.github/templates/actions/setup_java_and_scala"

      - name: Setup Hypergraph
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: "./.github/templates/actions/hypergraph/setup"

      - name: Cache Maven (~/.m2)
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Upload hypergraph artifacts to run CI tests
        uses: actions/upload-artifact@v4
        with:
          name: hypergraph
          path: .github/code/hypergraph
          retention-days: 7

      - name: Upload shared_jars artifacts to run CI tests
        uses: actions/upload-artifact@v4
        with:
          name: shared_jars
          path: .github/code/shared_jars
          retention-days: 7

  setup-project-template-metagraph:
    name: Setup project template metagraph
    runs-on: ubuntu-22.04
    needs: setup-hypergraph
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java and scala
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          JAVA_VERSION: 11
        uses: "./.github/templates/actions/setup_java_and_scala"

      - name: Cache Maven (~/.m2) - Reuse from setup hypergraph
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Setup project template metagraph
        with:
          METAGRAPH_NAME: project-template-metagraph
          TEMPLATE_NAME: project_template
          INCLUDE_DATA_LAYER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: "./.github/templates/actions/metagraph/setup"

      - name: Upload project-template-metagraph artifacts to run CI tests
        uses: actions/upload-artifact@v4
        with:
          name: project-template-metagraph
          path: .github/code/metagraphs/project-template-metagraph
          retention-days: 7