on:
  push:
    branches:
      - release/testnet

name: Testnet release

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Testnet release
    runs-on: ubuntu-22.04
    environment: testnet
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if the commit already has a tag starting with "v"
        id: check_tag
        run: |
          TAG=$(git tag --contains HEAD | grep -E '^v' || true)
          if [ -n "$TAG" ]; then
            echo "This commit has a tag starting with 'v': $TAG"
            echo "TAG_EXISTS=true" >> "$GITHUB_ENV"
          else
            echo "This commit does not have a tag starting with 'v'."
            echo "TAG_EXISTS=false" >> "$GITHUB_ENV"
          fi

      - name: Check branch and abort if necessary
        if: env.TAG_EXISTS == 'true'
        run: |
          echo "Aborting the action because the release should already exist."
          exit 1

      - name: Setup Java and scala
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          JAVA_VERSION: 21
        uses: "./.github/templates/actions/setup_java_and_scala"

      - name: Test
        run: sbt 'scalafmtCheckAll;scalafixAll --check --rules OrganizeImports;test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the pre-release version
        id: get_version
        run: |
          VERSION=$(npx commit-and-tag-version --dry-run --prerelease alpha | grep -oP 'tagging release v\K(.*)')
          [ -n "$VERSION" ] || { echo "ERROR: Failed to extract version from commit-and-tag-version"; exit 1; }
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set Git config
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Create release tag
        id: create_tag
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo "Release-As: $VERSION" >> $GITHUB_STEP_SUMMARY
          git tag -a v$VERSION -m "Release $VERSION"
          git push origin v$VERSION
          echo "release_tag=v$VERSION" >> "$GITHUB_OUTPUT"

      - name: Assembly 🚀
        run: sbt 'keytool/assembly;wallet/assembly;dagL0/assembly;dagL1/assembly'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: v${{ steps.get_version.outputs.VERSION }}

      - name: Copy dependencies
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          mkdir $VERSION
          cp ./modules/keytool/target/scala-2.13/tessellation-keytool-assembly-$VERSION.jar ./$VERSION/cl-keytool.jar
          cp ./modules/wallet/target/scala-2.13/tessellation-wallet-assembly-$VERSION.jar ./$VERSION/cl-wallet.jar
          cp ./modules/dag-l0/target/scala-2.13/tessellation-dag-l0-assembly-$VERSION.jar ./$VERSION/cl-node.jar
          cp ./modules/dag-l1/target/scala-2.13/tessellation-dag-l1-assembly-$VERSION.jar ./$VERSION/cl-dag-l1.jar

      - name: Create SHA-256 signature
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          RELEASE_SIGNING_KEY: ${{ secrets.RELEASE_SIGNING_KEY }}
        run: |
          umask 007
          mkdir ./ramdisk
          sudo mount -t tmpfs -o size=1M tmpfs ./ramdisk
          export KEY_NAME="$(uuidgen)"
          touch ./ramdisk/$KEY_NAME
          chmod 600 ./ramdisk/$KEY_NAME
          echo "$RELEASE_SIGNING_KEY" >  ./ramdisk/$KEY_NAME
          for jar in cl-keytool cl-wallet cl-node cl-dag-l1; do
            echo "$(sha256sum ./$VERSION/$jar.jar | sed 's/ .*//')" > ./$VERSION/$jar.sha256
            openssl dgst -sha256 -sign ./ramdisk/$KEY_NAME -out /dev/stdout ./$VERSION/$jar.sha256 | base64 > ./$VERSION/$jar.sig
          done

      - name: Cleanup ramdisk
        if: always()
        run: |
          sudo umount ./ramdisk
          rm -rf ./ramdisk

      - name: Send artifacts to S3
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.S3_REGION }}
          source: "./$VERSION"
          dest: "s3://${{ secrets.S3_BUCKET }}/testnet/tessellation/$VERSION"
          flags: --recursive --acl public-read
