name: Metagraph L1 - Currency Cluster

runs:
  using: "composite"
  steps:
    - name: Get the Metagraph ID
      shell: bash
      run: |
        cd .github/config/containers/metagraph-l0/genesis
        export METAGRAPH_ID=$(tail metagraph-l0-genesis.log -n 1000 | grep -o "Address from genesis data is .*" | grep -o "DAG.*")
        echo "METAGRAPH_ID=$METAGRAPH_ID"
        echo "METAGRAPH_ID=$METAGRAPH_ID" >> $GITHUB_ENV

    - name: Run Metagraph L1 - Currency Initial Validator
      uses: "./.github/templates/metagraph_currency_l1/initial_validator"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        CL_PUBLIC_HTTP_PORT: 9700
        CL_P2P_HTTP_PORT: 9701
        CL_CLI_HTTP_PORT: 9702
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L0_PEER_HTTP_PORT: 9400

    - name: Run Metagraph L1 - Currency Validator - 1
      uses: "./.github/templates/metagraph_currency_l1/validator"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        CL_PUBLIC_HTTP_PORT: 9800
        CL_P2P_HTTP_PORT: 9801
        CL_CLI_HTTP_PORT: 9802
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L0_PEER_HTTP_PORT: 9400
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: 9701
        NODE_NUMBER: 1

    - name: Run Metagraph L1 - Currency Validator - 2
      uses: "./.github/templates/metagraph_currency_l1/validator"
      with:
        METAGRAPH_ID: ${{ env.METAGRAPH_ID }}
        CL_PUBLIC_HTTP_PORT: 9900
        CL_P2P_HTTP_PORT: 9901
        CL_CLI_HTTP_PORT: 9902
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L0_PEER_HTTP_PORT: 9400
        CL_L1_INITIAL_VALIDATOR_P2P_PORT: 9701
        NODE_NUMBER: 2